version: '3.1'

services:

  mongo:
    image: mongo
    restart: always # default port 27017
    ports: 
      - 27017:27017
    volumes: 
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: barter
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on: 
      - "mongo"
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 10000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: barter